export const allAction = {
  SET_ITEM: "SET_ITEM",
  ADD_ITEM: "ADD_ITEM",
  DELETE_ITEM: "DELETE_ITEM",
  SET_FINISH: "SET_FINISH",

  SET_SCREEN_WIDTH: "SET_SCREEN_WIDTH",

  //    Modal Reducer
  SET_MODAL: "SET_MODAL",
  CLOSE_MODAL: "CLOSE_MODAL",
}
