name: eslint
on:
  pull_request:
    branches:
      - master
      - main
jobs:
  eslint:
    name: runner / eslint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: yarn install
      - uses: reviewdog/action-eslint@v1.14.0
        with:
          reporter: github-pr-review
          github_token: ${{secrets.GITHUB_TOKEN}}
          fail_on_error: true
